class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start4'
        self.MirrorCommand = 'mirror4'
        self.UnzipMirrorCommand = 'unzipmirror4'
        self.TarMirrorCommand = 'tarmirror4'
        self.ZipMirrorCommand = 'zipmirror4'
        self.CancelMirror = 'cancel4'
        self.CancelAllCommand = 'cancelall'
        self.ListCommand = 'search'
        self.StatusCommand = 'status4'
        self.AuthorizedUsersCommand = 'users'
        self.AuthorizeCommand = 'authorize'
        self.UnAuthorizeCommand = 'unauthorize'
        self.AddSudoCommand = 'addsudo'
        self.RmSudoCommand = 'rmsudo'
        self.PingCommand = 'ping'
        self.RestartCommand = 'restart4'
        self.StatsCommand = 'stats4'
        self.HelpCommand = 'help4'
        self.LogCommand = 'log'
        self.SpeedCommand = 'speedtest4'
        self.CloneCommand = 'clone4'
        self.CountCommand = 'count4'
        self.WatchCommand = 'watch4'
        self.TarWatchCommand = 'tarwatch4'
        self.DeleteCommand = 'del4'
        self.ShellCommand = 'shell'
        self.ExecHelpCommand = 'exechelp'

BotCommands = _BotCommands()
